branch-defaults:
  default:
    environment: img-processing-micro-elb-dev2
environment-defaults:
  img-processing-micro-elb-dev2:
    branch: null
    repository: null
global:
  application_name: img-processing-micro-elb
  default_ec2_keyname: vockey
  default_platform: Node.js 20 running on 64bit Amazon Linux 2023
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: null
  workspace_type: Application
